package tela;

import tela.tm.ExemplarTM;
import control.ExemplarControl;
import control.LivroControl;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import model.Exemplar;
import model.Livro;

/**
 * CadastroExemplarView
 *
 * @author Jean Barcellos <jeanbarcellos@hotmail.com>
 */
public class CadastroExemplarView extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1546267700893476533L;

    private ExemplarControl exemplarControl;
    private LivroControl livroControl;
    private ExemplarTM exemplarTM;
    private Livro livro;

    /**
     * Creates new form CadastroExemplaresView
     */
    public CadastroExemplarView(int id) {
        initComponents();
                
        this.livroControl = new LivroControl();
        this.livro = this.livroControl.getLivro(id);

        this.exemplarControl = new ExemplarControl();

        this.textLivroId.setText("" + this.livro.getId());
        this.textLivroTitulo.setText(this.livro.getTitulo());
        this.textLivroAutor.setText(this.livro.getAutor());
        
        this.carregarTabela();

        this.gerenciarBotoes(true, false, false, false, false);
    }

    /**
     * Posiciona o painel no mei da tela
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * Popula a tabela com a lista de exemplares
     */
    private void carregarTabela() {
        List<Exemplar> lista = this.exemplarControl.listar(livro.getId());

        this.exemplarTM = new ExemplarTM(lista);
        tableExemplarLista.setModel(exemplarTM);
        tableExemplarLista.getColumnModel().getColumn(0).setPreferredWidth(50);
        tableExemplarLista.getColumnModel().getColumn(1).setPreferredWidth(300);
        tableExemplarLista.getColumnModel().getColumn(2).setPreferredWidth(400);
    }

    /**
     * Gerencia botões do Fomurlário
     *
     * @param novo Botão Novo
     * @param editar Botão Editar
     * @param excluir Botão Excluir
     * @param salvar Botão Salvar
     * @param cancelar Botão Cancelar
     */
    private void gerenciarBotoes(boolean novo, boolean editar, boolean excluir, boolean salvar, boolean cancelar) {
        this.buttonNovo.setEnabled(novo);
        this.buttonEditar.setEnabled(editar);
        this.buttonExcluir.setEnabled(excluir);
        this.buttonSalvar.setEnabled(salvar);
        this.buttonCancelar.setEnabled(cancelar);
    }

    /**
     * Valida o formulário;
     *
     * @return
     */
    private boolean validarFormulario() {
        // Campo Edicao
        if (textEdicao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você deve preencher a edição do exemplar.");
            textEdicao.requestFocus();
            return false;
        }
        // Campo Edicao
        if (textLocalizacao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você deve preencher a localização do exemplar.");
            textLocalizacao.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * Limpa os campos do formulário
     */
    private void limparFormulario() {
        textId.setText("");
        textEdicao.setText("");
        textLocalizacao.setText("");
    }

    /**
     * Libera o formulário para edição
     */
    private void liberarFormulario() {
        textEdicao.setEnabled(true);
        textLocalizacao.setEnabled(true);
    }

    /**
     * Bloqueia o formulário contra edições
     */
    private void bloquearFormulario() {
        textEdicao.setEnabled(false);
        textLocalizacao.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLivro = new javax.swing.JPanel();
        labelLivroId = new javax.swing.JLabel();
        textLivroId = new javax.swing.JTextField();
        labelLivroTitulo = new javax.swing.JLabel();
        textLivroTitulo = new javax.swing.JTextField();
        labelLivroAutor = new javax.swing.JLabel();
        textLivroAutor = new javax.swing.JTextField();
        scrollPaneExemplarLista = new javax.swing.JScrollPane();
        tableExemplarLista = new javax.swing.JTable();
        buttonNovo = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        panelExemplar = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        labelEdicao = new javax.swing.JLabel();
        textEdicao = new javax.swing.JTextField();
        labelLocalizacao = new javax.swing.JLabel();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        textLocalizacao = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Exemplares do Livro");

        panelLivro.setBorder(javax.swing.BorderFactory.createTitledBorder("Livro"));

        labelLivroId.setText("ID:");

        textLivroId.setEditable(false);

        labelLivroTitulo.setText("Título:");

        textLivroTitulo.setEditable(false);

        labelLivroAutor.setText("Edição:");

        textLivroAutor.setEditable(false);

        javax.swing.GroupLayout panelLivroLayout = new javax.swing.GroupLayout(panelLivro);
        panelLivro.setLayout(panelLivroLayout);
        panelLivroLayout.setHorizontalGroup(
            panelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLivroAutor)
                    .addComponent(labelLivroTitulo)
                    .addComponent(labelLivroId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLivroLayout.createSequentialGroup()
                        .addComponent(textLivroId, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textLivroAutor)
                    .addComponent(textLivroTitulo))
                .addContainerGap())
        );
        panelLivroLayout.setVerticalGroup(
            panelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivroLayout.createSequentialGroup()
                .addGroup(panelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLivroId)
                    .addComponent(textLivroId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLivroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLivroTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLivroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLivroAutor))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        tableExemplarLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Edição", "Localização"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableExemplarLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableExemplarLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableExemplarListaMouseClicked(evt);
            }
        });
        scrollPaneExemplarLista.setViewportView(tableExemplarLista);

        buttonNovo.setText("Novo");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        panelExemplar.setBorder(javax.swing.BorderFactory.createTitledBorder("Exemplar"));

        labelId.setText("ID:");

        textId.setEditable(false);
        textId.setEnabled(false);

        labelEdicao.setText("Edição:");

        textEdicao.setEnabled(false);

        labelLocalizacao.setText("Localização:");

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        textLocalizacao.setEnabled(false);

        javax.swing.GroupLayout panelExemplarLayout = new javax.swing.GroupLayout(panelExemplar);
        panelExemplar.setLayout(panelExemplarLayout);
        panelExemplarLayout.setHorizontalGroup(
            panelExemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExemplarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelEdicao)
                    .addComponent(labelId)
                    .addComponent(labelLocalizacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExemplarLayout.createSequentialGroup()
                        .addComponent(buttonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCancelar))
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panelExemplarLayout.setVerticalGroup(
            panelExemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExemplarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelExemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEdicao))
                .addGap(4, 4, 4)
                .addGroup(panelExemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocalizacao)
                    .addComponent(textLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelExemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollPaneExemplarLista, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addComponent(panelExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneExemplarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNovo)
                    .addComponent(buttonExcluir)
                    .addComponent(buttonEditar))
                .addGap(18, 18, 18)
                .addComponent(panelExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed

        boolean validacao = this.validarFormulario();

        if (validacao) {
            String edicao = textEdicao.getText();
            String localizacao = textLocalizacao.getText();
            
            Exemplar exemplar = new Exemplar();
            boolean retorno;

            if (textId.getText().equals("")) { // Cadstrar

                exemplar.setLivro(this.livro);
                exemplar.setEdicao(edicao);
                exemplar.setLocalizacao(localizacao);

                retorno = this.exemplarControl.inserir(exemplar);

                if (retorno) {
                    this.carregarTabela();

                    JOptionPane.showMessageDialog(null, "Exemplar Cadastrado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao Tentar cadastrar Exemplar.");
                }

            } else { // Editar

                exemplar.setId(Integer.parseInt(textId.getText()));
                exemplar.setEdicao(edicao);
                exemplar.setLocalizacao(localizacao);

                retorno = this.exemplarControl.alterar(exemplar);

                if (retorno) {
                    JOptionPane.showMessageDialog(null, "Exemplar alterado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao Tentar alterar informações do exemplar.");
                }
            }
        }

        this.limparFormulario();

        this.bloquearFormulario();

        this.gerenciarBotoes(true, false, false, false, false);
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.limparFormulario();

        this.bloquearFormulario();

        gerenciarBotoes(true, false, false, false, false);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void tableExemplarListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableExemplarListaMouseClicked
        this.bloquearFormulario();

        int indice = tableExemplarLista.getSelectedRow();
        if (indice >= 0 && indice < this.exemplarTM.getRowCount()) {
            Exemplar temp = exemplarTM.getExemplar(indice);
            textId.setText("" + temp.getId());
            textEdicao.setText(temp.getEdicao());
            textLocalizacao.setText(temp.getLocalizacao());
        }

        this.gerenciarBotoes(true, true, true, false, false);
    }//GEN-LAST:event_tableExemplarListaMouseClicked

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        this.limparFormulario();

        this.liberarFormulario();

        textEdicao.requestFocus();

        gerenciarBotoes(false, false, false, true, true);
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        this.liberarFormulario();

        this.gerenciarBotoes(false, false, false, true, true);
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        Object[] options = {"Sim", "Cancelar"};
        int retornoExcluir = JOptionPane.showOptionDialog(null, "Tens certeza que deseja excluir ...?", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (retornoExcluir == JOptionPane.YES_OPTION) {

            int idExcluir = Integer.parseInt(textId.getText());

            boolean retorno = this.exemplarControl.excluir(idExcluir);

            if (retorno) {
                this.carregarTabela();
                JOptionPane.showMessageDialog(null, "Exemplar excluído com sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao excluír o exemplar.");
            }

            this.limparFormulario();

            this.bloquearFormulario();
        } else {

        }

        this.gerenciarBotoes(true, false, false, false, false);
    }//GEN-LAST:event_buttonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel labelEdicao;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelLivroAutor;
    private javax.swing.JLabel labelLivroId;
    private javax.swing.JLabel labelLivroTitulo;
    private javax.swing.JLabel labelLocalizacao;
    private javax.swing.JPanel panelExemplar;
    private javax.swing.JPanel panelLivro;
    private javax.swing.JScrollPane scrollPaneExemplarLista;
    private javax.swing.JTable tableExemplarLista;
    private javax.swing.JTextField textEdicao;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textLivroAutor;
    private javax.swing.JTextField textLivroId;
    private javax.swing.JTextField textLivroTitulo;
    private javax.swing.JTextField textLocalizacao;
    // End of variables declaration//GEN-END:variables
}
