package tela;

import tela.tm.ExemplaresPegosTM;
import control.AlunoControl;
import control.CursoControl;
import control.EmprestimoControl;
import java.awt.Dimension;

import model.Curso;
import java.util.List;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Emprestimo;

/**
 *
 * @author Jean Barcellos <jeanbarcellos@hotmail.com>
 */
public class CadastroAlunoDetalheView extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -6170983364654323855L;

    private AlunoControl alunoControl;
    private CursoControl cursoControl;
    private EmprestimoControl emprestimoControl;
    private ExemplaresPegosTM exemplaresTM;
    private Aluno aluno;

    /**
     * Creates new form CadastroAlunoDetalheView
     *
     * @param id ID do Aluno a ser detalhado
     */
    public CadastroAlunoDetalheView(int id) {
        initComponents();

        this.alunoControl = new AlunoControl();
        this.cursoControl = new CursoControl();
        this.emprestimoControl = new EmprestimoControl();

        this.popularFormulario(id);

        this.gerenciarBotoes(false, false, true);

        this.bloquearFormulario();
        
        this.carregarTabela();
    }

    private void popularFormulario(int id) {
        this.aluno = this.alunoControl.getAluno(id);

        textId.setText("" + this.aluno.getId());
        textNome.setText(this.aluno.getNome());
        textMatricula.setText("" + this.aluno.getMatricula());
        textCurso.setText(this.aluno.getCurso().getNome());

    }

    /**
     * Posiciona o painel no mei da tela
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * Popula a tabela com a lista de cursos
     */
    private void carregarTabela() {
        List<Emprestimo> lista = this.emprestimoControl.getExemplaresPegos(aluno.getId());

        this.exemplaresTM = new ExemplaresPegosTM(lista);
        tableLivros.setModel(exemplaresTM);
        tableLivros.getColumnModel().getColumn(0).setPreferredWidth(250);
        tableLivros.getColumnModel().getColumn(1).setPreferredWidth(150);
        tableLivros.getColumnModel().getColumn(2).setPreferredWidth(100);
        tableLivros.getColumnModel().getColumn(3).setPreferredWidth(55);
        tableLivros.getColumnModel().getColumn(4).setPreferredWidth(55);
    }

    /**
     * Valida o formulário;
     *
     * @return
     */
    private boolean validarFormulario() {
        // Campo Nome
        if (textNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você deve preencher o nome.");
            textNome.requestFocus();
            return false;
        }
        // Campo Nome
        if (textMatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você deve preencher a matrícula.");
            textMatricula.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * Libera o formulário para edição
     */
    private void liberarFormulario() {
        textNome.setEnabled(true);
        textMatricula.setEnabled(true);
        textCurso.setEnabled(false);
    }

    /**
     * Bloqueia o formulário contra edições
     */
    private void bloquearFormulario() {
        textNome.setEnabled(false);
        textMatricula.setEnabled(false);
        textCurso.setEnabled(false);
    }

    /**
     * Gerenciar os botões
     *
     * @param salvar Button Salvar
     * @param cancelar BUtton Cancelar
     * @param editar Button Editar
     */
    private void gerenciarBotoes(boolean salvar, boolean cancelar, boolean editar) {
        buttonSalvar.setEnabled(salvar);
        buttonCancelar.setEnabled(cancelar);
        buttonEditar.setEnabled(editar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAluno = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        labelMatricula = new javax.swing.JLabel();
        textMatricula = new javax.swing.JTextField();
        curso = new javax.swing.JLabel();
        textCurso = new javax.swing.JTextField();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        panelLivros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivros = new javax.swing.JTable();
        buttonEditar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Detalhes do Aluno");

        panelAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Aluno"));

        labelId.setText("ID:");

        textId.setEditable(false);

        labelNome.setText("Nome:");

        labelMatricula.setText("Matrícula:");

        curso.setText("Curso:");

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlunoLayout = new javax.swing.GroupLayout(panelAluno);
        panelAluno.setLayout(panelAlunoLayout);
        panelAlunoLayout.setHorizontalGroup(
            panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelId)
                    .addComponent(curso)
                    .addComponent(labelMatricula)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlunoLayout.createSequentialGroup()
                        .addGroup(panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAlunoLayout.createSequentialGroup()
                                .addComponent(buttonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonCancelar)))
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addComponent(textNome)
                    .addComponent(textCurso))
                .addContainerGap())
        );
        panelAlunoLayout.setVerticalGroup(
            panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricula)
                    .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curso)
                    .addComponent(textCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLivros.setBorder(javax.swing.BorderFactory.createTitledBorder("Livros emprestados"));

        tableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Edição", "Data Emprestimo", "Data Entrega"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableLivros);
        if (tableLivros.getColumnModel().getColumnCount() > 0) {
            tableLivros.getColumnModel().getColumn(1).setResizable(false);
            tableLivros.getColumnModel().getColumn(2).setResizable(false);
            tableLivros.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout panelLivrosLayout = new javax.swing.GroupLayout(panelLivros);
        panelLivros.setLayout(panelLivrosLayout);
        panelLivrosLayout.setHorizontalGroup(
            panelLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLivrosLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelLivrosLayout.setVerticalGroup(
            panelLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLivrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        buttonEditar.setText("Editar Dados");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonEditar))
                        .addGap(0, 364, Short.MAX_VALUE))
                    .addComponent(panelLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed

        boolean validacao = this.validarFormulario();

        if (validacao) {
            String nome = textNome.getText();
            int matricula = Integer.parseInt(textMatricula.getText());

            aluno.setNome(nome);
            aluno.setMatricula(matricula);

            boolean retorno = alunoControl.alterar(aluno);

            if (retorno) {
                CadastroAlunoView.carregarTabela();
                JOptionPane.showMessageDialog(null, "Aluno alterado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar alterar o aluno.");
            }
            this.bloquearFormulario();
            this.gerenciarBotoes(false, false, true);
        }
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        this.liberarFormulario();

        this.gerenciarBotoes(true, true, false);
    }//GEN-LAST:event_buttonEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel curso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelNome;
    private javax.swing.JPanel panelAluno;
    private javax.swing.JPanel panelLivros;
    private javax.swing.JTable tableLivros;
    private javax.swing.JTextField textCurso;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textMatricula;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables

    public class ComboBoxItem {

        private int id;
        private String value;

        public ComboBoxItem() {
            id = 0;
            value = "";
        }

        public ComboBoxItem(int id, String value) {
            this.id = id;
            this.value = value;
        }

        public int getId() {
            return this.id;
        }

        public String getValue() {
            return this.value;
        }

        public void setID(int id) {
            this.id = id;
        }

        public void setValue(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return value;
        }

    }
}
