/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import control.CursoControl;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import model.Curso;

/**
 *
 * @author Jean Barcellos <jeanbarcellos@hotmail.com>
 */
public class CadastroCursoView extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private CursoControl cursoControl;
    private CursoTM Modelo;

    /**
     * Creates new form CadastroClientesView
     */
    public CadastroCursoView() {
        initComponents();
        this.cursoControl = new CursoControl();
        this.carregarTabela();
        this.gerenciarBotoes(true, false, false, false, false);
    }

    /**
     * Posiciona no meio
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * Gerencia botões do Fomurlário
     *
     * @param novo Botão Novo
     * @param editar Botão Editar
     * @param excluir Botão Excluir
     * @param salvar Botão Salvar
     * @param cancelar Botão Cancelar
     */
    private void gerenciarBotoes(boolean novo, boolean editar, boolean excluir, boolean salvar, boolean cancelar) {
        this.buttonNovo.setEnabled(novo);
        this.buttonEditar.setEnabled(editar);
        this.buttonExcluir.setEnabled(excluir);
        this.buttonSalvar.setEnabled(salvar);
        this.buttonCarncelar.setEnabled(cancelar);
    }

    /**
     * Valida o formulário;
     *
     * @return
     */
    private boolean validarFormulario() {
        if (textNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você deve preencher o nome do curso");
            textNome.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * Limpa o formulário
     */
    private void limparFormulario() {
        textId.setText("");
        textNome.setText("");
    }

    private void liberarFormulario() {
        textNome.setEnabled(true);
    }

    private void bloquearFormulario() {
        textNome.setEnabled(false);
    }

    private void carregarTabela() {
        List<Curso> lista = this.cursoControl.getCursos();

        this.Modelo = new CursoTM(lista);
        tableCursoLista.setModel(Modelo);

        tableCursoLista.getColumnModel().getColumn(0).setPreferredWidth(100);
        tableCursoLista.getColumnModel().getColumn(1).setPreferredWidth(250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCurso = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        buttonSalvar = new javax.swing.JButton();
        buttonCarncelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCursoLista = new javax.swing.JTable();
        buttonNovo = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Cursos");
        setVisible(true);

        panelCurso.setBorder(javax.swing.BorderFactory.createTitledBorder("Curso"));

        labelId.setText("ID:");

        textId.setEditable(false);
        textId.setEnabled(false);
        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });

        labelNome.setText("Nome:");

        textNome.setEnabled(false);
        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCarncelar.setText("Cancelar");
        buttonCarncelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCarncelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCursoLayout = new javax.swing.GroupLayout(panelCurso);
        panelCurso.setLayout(panelCursoLayout);
        panelCursoLayout.setHorizontalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNome)
                    .addComponent(labelId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNome)
                    .addGroup(panelCursoLayout.createSequentialGroup()
                        .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCursoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCarncelar)
                .addGap(69, 69, 69))
        );
        panelCursoLayout.setVerticalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonCarncelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableCursoLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCursoLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCursoListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCursoLista);

        buttonNovo.setText("Novo");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonExcluir)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNovo)
                    .addComponent(buttonExcluir)
                    .addComponent(buttonEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento do botão Salvar
     *
     * @param evt
     */
    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed

        boolean validacao = this.validarFormulario();

        boolean retorno;

        if (validacao) {
            String nome = textNome.getText();
            Curso curso = new Curso();

            if (textId.getText().equals("")) {

                curso.setNome(nome);

                retorno = this.cursoControl.inserir(curso);

                if (retorno) {
                    JOptionPane.showMessageDialog(null, "Curso Cadastrado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao Tentar cadastrar Curso.");
                }

            } else {
                int id = Integer.parseInt(textId.getText());

                curso.setId(id);
                curso.setNome(nome);

                retorno = this.cursoControl.alterar(curso);

                if (retorno) {
                    JOptionPane.showMessageDialog(null, "Curso alterado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao Tentar alterar informações do curso.");
                }
            }
        }

        this.limparFormulario();
        this.bloquearFormulario();

        gerenciarBotoes(true, false, false, false, false);

    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonCarncelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCarncelarActionPerformed
        this.limparFormulario();
        this.bloquearFormulario();

        gerenciarBotoes(true, false, false, false, false);
    }//GEN-LAST:event_buttonCarncelarActionPerformed

    private void tableCursoListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCursoListaMouseClicked
        int index = tableCursoLista.getSelectedRow();
        if (index >= 0 && index < this.Modelo.getRowCount()) {
            Curso temp = Modelo.getCurso(index);
            textId.setText("" + temp.getId());
            textNome.setText(temp.getNome());
        }

        this.gerenciarBotoes(true, true, true, false, false);
    }//GEN-LAST:event_tableCursoListaMouseClicked

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        this.limparFormulario();
        this.liberarFormulario();

        textNome.setEnabled(true);
        textNome.requestFocus();

        gerenciarBotoes(false, false, false, true, true);
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        this.gerenciarBotoes(false, false, false, true, true);

        textNome.setEnabled(true);
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        Object[] options = {"Sim", "Cancelar"};
        int retornoExcluir = JOptionPane.showOptionDialog(null, "Tens certeza que deseja excluir ...?", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (retornoExcluir == JOptionPane.YES_OPTION) {

            int idExcluir = Integer.parseInt(textId.getText());

            boolean retorno = this.cursoControl.excluir(idExcluir);

            if (retorno) {
                JOptionPane.showMessageDialog(null, "Curso excluído com sucesso.");

                this.carregarTabela();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao excluír o curso.");
            }

            this.limparFormulario();
        } else {
            JOptionPane.showMessageDialog(null, "Não exluir");
        }

        this.bloquearFormulario();

        this.gerenciarBotoes(true, false, false, false, false);
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed

    }//GEN-LAST:event_textNomeActionPerformed

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed

    }//GEN-LAST:event_textIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCarncelar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNome;
    private javax.swing.JPanel panelCurso;
    private javax.swing.JTable tableCursoLista;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
