/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jean Barcellos <jeanbarcellos@hotmail.com>
 */
public class Principal extends javax.swing.JFrame {

    private static final long serialVersionUID = 7695201886374250202L;

    /**
     * Creates new form PrincipalTela
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuItemCadastroCurso = new javax.swing.JMenuItem();
        menuItemCadastroAluno = new javax.swing.JMenuItem();
        menuItemCadastroProfessor = new javax.swing.JMenuItem();
        menuItemCadastroLivro = new javax.swing.JMenuItem();
        menuItemCadastroExemplar = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuProcedimento = new javax.swing.JMenu();
        menuItemProcEmprestimo = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Universitária");

        desktop.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/page_edit.png"))); // NOI18N
        menuCadastro.setText("Cadastro");

        menuItemCadastroCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/folder.png"))); // NOI18N
        menuItemCadastroCurso.setText("Curso");
        menuItemCadastroCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroCursoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroCurso);

        menuItemCadastroAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/user.png"))); // NOI18N
        menuItemCadastroAluno.setText("Aluno");
        menuItemCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroAlunoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroAluno);

        menuItemCadastroProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/user_gray.png"))); // NOI18N
        menuItemCadastroProfessor.setText("Professor");
        menuItemCadastroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroProfessorActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroProfessor);

        menuItemCadastroLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/book_open.png"))); // NOI18N
        menuItemCadastroLivro.setText("Livro");
        menuItemCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroLivroActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroLivro);

        menuItemCadastroExemplar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/book.png"))); // NOI18N
        menuItemCadastroExemplar.setText("Exemplar");
        menuItemCadastroExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroExemplarActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroExemplar);

        barraMenuPrincipal.add(menuCadastro);

        menuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/zoom.png"))); // NOI18N
        menuConsulta.setText("Consulta");
        barraMenuPrincipal.add(menuConsulta);

        menuProcedimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/cog.png"))); // NOI18N
        menuProcedimento.setText("Procedimentos");

        menuItemProcEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/cart.png"))); // NOI18N
        menuItemProcEmprestimo.setText("Empréstimo");
        menuItemProcEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProcEmprestimoActionPerformed(evt);
            }
        });
        menuProcedimento.add(menuItemProcEmprestimo);

        barraMenuPrincipal.add(menuProcedimento);

        menuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/server.png"))); // NOI18N
        menuSistema.setText("Sistema");

        menuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/stop.png"))); // NOI18N
        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuSistema.add(menuItemSair);

        barraMenuPrincipal.add(menuSistema);

        setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * EVENTOS *****************************************************************
     */
    /**
     * Evento do Menu
     *
     * @param evt
     */
    private void menuItemCadastroCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroCursoActionPerformed
        CadastroCursoView cadastroClientesView = new CadastroCursoView();
        desktop.add(cadastroClientesView);
        cadastroClientesView.setPosicao();
        cadastroClientesView.setVisible(true);
    }//GEN-LAST:event_menuItemCadastroCursoActionPerformed

    private void menuItemCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroAlunoActionPerformed

    }//GEN-LAST:event_menuItemCadastroAlunoActionPerformed

    private void menuItemCadastroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCadastroProfessorActionPerformed

    private void menuItemCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCadastroLivroActionPerformed

    private void menuItemCadastroExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroExemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCadastroExemplarActionPerformed

    private void menuItemProcEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProcEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemProcEmprestimoActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed

    }//GEN-LAST:event_menuItemSairActionPerformed

    /**
     * Classe Principal
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                Nimbus
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame seuFrame = new Principal();
                seuFrame.setExtendedState(seuFrame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
                seuFrame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuItemCadastroAluno;
    private javax.swing.JMenuItem menuItemCadastroCurso;
    private javax.swing.JMenuItem menuItemCadastroExemplar;
    private javax.swing.JMenuItem menuItemCadastroLivro;
    private javax.swing.JMenuItem menuItemCadastroProfessor;
    private javax.swing.JMenuItem menuItemProcEmprestimo;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuProcedimento;
    private javax.swing.JMenu menuSistema;
    // End of variables declaration//GEN-END:variables
}
