/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.tm.LivroTM;
import control.LivroControl;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import model.Livro;

/**
 *
 * @author Jean Barcellos <jeanbarcellos@hotmail.com>
 */
public class CadastroLivroView extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 7642045903897247428L;
    private LivroControl livroControl;
    private LivroTM livroTM;

    /**
     * Creates new form CadastroLivroView
     */
    public CadastroLivroView() {
        initComponents();
        this.livroControl = new LivroControl();

        this.carregarTabela();

        this.gerenciarBotoes(true, false, false, false, false, false);
    }

    /**
     * Posiciona o painel no mei da tela
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * Popula a tabela com a lista de livros
     */
    private void carregarTabela() {
        List<Livro> lista = this.livroControl.getLivros();

        this.livroTM = new LivroTM(lista);
        tableLivroLista.setModel(livroTM);
        tableLivroLista.getColumnModel().getColumn(0).setPreferredWidth(20);
        tableLivroLista.getColumnModel().getColumn(1).setPreferredWidth(300);
        tableLivroLista.getColumnModel().getColumn(1).setPreferredWidth(300);
    }

    /**
     * Gerencia botões do Fomurlário
     *
     * @param novo Botão Novo
     * @param editar Botão Editar
     * @param excluir Botão Excluir
     * @param salvar Botão Salvar
     * @param cancelar Botão Cancelar
     */
    private void gerenciarBotoes(boolean novo, boolean editar, boolean excluir, boolean salvar, boolean cancelar, boolean exemplares) {
        this.buttonNovo.setEnabled(novo);
        this.buttonEditar.setEnabled(editar);
        this.buttonExcluir.setEnabled(excluir);
        this.buttonSalvar.setEnabled(salvar);
        this.buttonCancelar.setEnabled(cancelar);
        this.buttonExemplares.setEnabled(exemplares);
    }

    /**
     * Valida o formulário;
     *
     * @return
     */
    private boolean validarFormulario() {
        // Campo Titulo
        if (textTitulo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você deve preencher o Título do livro.");
            textTitulo.requestFocus();
            return false;
        }
        // Campo Titulo
        if (textAutor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você deve preencher o Autor do livro.");
            textAutor.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * Limpa os campos do formulário
     */
    private void limparFormulario() {
        textId.setText("");
        textTitulo.setText("");
        textAutor.setText("");
    }

    /**
     * Libera o formulário para edição
     */
    private void liberarFormulario() {
        textTitulo.setEnabled(true);
        textAutor.setEnabled(true);
    }

    /**
     * Bloqueia o formulário contra edições
     */
    private void bloquearFormulario() {
        textTitulo.setEnabled(false);
        textAutor.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCurso = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        textTitulo = new javax.swing.JTextField();
        labelAutor = new javax.swing.JLabel();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        textAutor = new javax.swing.JTextField();
        scrollPaneLivroLista = new javax.swing.JScrollPane();
        tableLivroLista = new javax.swing.JTable();
        buttonNovo = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        buttonExemplares = new javax.swing.JButton();

        setClosable(true);
        setTitle("Livros");

        panelCurso.setBorder(javax.swing.BorderFactory.createTitledBorder("Livro"));

        labelId.setText("ID:");

        textId.setEditable(false);
        textId.setEnabled(false);

        labelTitulo.setText("Titulo:");

        textTitulo.setEnabled(false);

        labelAutor.setText("Autor:");

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        textAutor.setEnabled(false);

        javax.swing.GroupLayout panelCursoLayout = new javax.swing.GroupLayout(panelCurso);
        panelCurso.setLayout(panelCursoLayout);
        panelCursoLayout.setHorizontalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAutor)
                    .addComponent(labelTitulo)
                    .addComponent(labelId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCursoLayout.createSequentialGroup()
                        .addComponent(buttonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCancelar))
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelCursoLayout.setVerticalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAutor)
                    .addComponent(textAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableLivroLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Autor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLivroLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableLivroLista.getTableHeader().setReorderingAllowed(false);
        tableLivroLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLivroListaMouseClicked(evt);
            }
        });
        scrollPaneLivroLista.setViewportView(tableLivroLista);

        buttonNovo.setText("Novo");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        buttonExemplares.setText("Gerenciar Exemplares");
        buttonExemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExemplaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonEditar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonExemplares)
                            .addGap(5, 5, 5)
                            .addComponent(buttonExcluir))
                        .addComponent(scrollPaneLivroLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneLivroLista, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNovo)
                    .addComponent(buttonExcluir)
                    .addComponent(buttonEditar)
                    .addComponent(buttonExemplares))
                .addGap(18, 18, 18)
                .addComponent(panelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed

        boolean validacao = this.validarFormulario();

        if (validacao) {
            String titulo = textTitulo.getText();
            String autor = textAutor.getText();
            Livro livro = new Livro();
            boolean retorno;

            if (textId.getText().equals("")) { // Cadstrar

                livro.setTitulo(titulo);
                livro.setAutor(autor);

                retorno = this.livroControl.inserir(livro);

                if (retorno) {
                    this.carregarTabela();

                    JOptionPane.showMessageDialog(null, "Livro Cadastrado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao Tentar cadastrar Livro.");
                }

            } else { // Editar

                livro.setId(Integer.parseInt(textId.getText()));
                livro.setTitulo(titulo);
                livro.setAutor(autor);

                retorno = this.livroControl.alterar(livro);

                if (retorno) {
                    JOptionPane.showMessageDialog(null, "Livro alterado com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao Tentar alterar informações do livro.");
                }
            }
        }

        this.limparFormulario();

        this.bloquearFormulario();

        this.gerenciarBotoes(true, false, false, false, false, false);
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.limparFormulario();

        this.bloquearFormulario();

        gerenciarBotoes(true, false, false, false, false, false);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void tableLivroListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLivroListaMouseClicked
        this.bloquearFormulario();

        int indice = tableLivroLista.getSelectedRow();
        if (indice >= 0 && indice < this.livroTM.getRowCount()) {
            Livro temp = livroTM.getLivro(indice);
            textId.setText("" + temp.getId());
            textTitulo.setText(temp.getTitulo());
            textAutor.setText(temp.getAutor());
        }

        this.gerenciarBotoes(true, true, true, false, false, true);
    }//GEN-LAST:event_tableLivroListaMouseClicked

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed
        this.limparFormulario();

        this.liberarFormulario();

        textTitulo.requestFocus();

        gerenciarBotoes(false, false, false, true, true, false);
    }//GEN-LAST:event_buttonNovoActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        this.liberarFormulario();

        this.gerenciarBotoes(false, false, false, true, true, false);
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        Object[] options = {"Sim", "Cancelar"};
        int retornoExcluir = JOptionPane.showOptionDialog(null, "Tens certeza que deseja excluir ...?", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (retornoExcluir == JOptionPane.YES_OPTION) {

            int idExcluir = Integer.parseInt(textId.getText());

            boolean retorno = this.livroControl.excluir(idExcluir);

            if (retorno) {
                this.carregarTabela();
                JOptionPane.showMessageDialog(null, "Livro excluído com sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao excluír o livro.");
            }

            this.limparFormulario();

            this.bloquearFormulario();
        } else {

        }

        this.gerenciarBotoes(true, false, false, false, false, false);
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void buttonExemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExemplaresActionPerformed
        int linha = tableLivroLista.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma livro para gerenciar seus exemplares.");
        } else {
            int idEditar = (int) tableLivroLista.getValueAt(linha, 0);

            CadastroExemplarView detalheView = new CadastroExemplarView(idEditar);
            Principal.desktop.add(detalheView);
            detalheView.getFont();
            detalheView.setPosicao();
            detalheView.setVisible(true);
        }
    }//GEN-LAST:event_buttonExemplaresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonExemplares;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelCurso;
    private javax.swing.JScrollPane scrollPaneLivroLista;
    private javax.swing.JTable tableLivroLista;
    private javax.swing.JTextField textAutor;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textTitulo;
    // End of variables declaration//GEN-END:variables
}
