package view;

import control.EmprestimoControl;
import java.awt.Dimension;
import java.util.List;
import model.Emprestimo;
import view.tm.EmprestimosAtivosTM;

/**
 *
 * @author Jean Barcellos <jeanbarcellos@hotmail.com>
 */
public class EmprestimoLivroView extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmprestimoLivroView
     */
    public EmprestimoLivroView() {
        initComponents();
        
        carregarTabela();
    }

    /**
     * Posiciona o painel no mei da tela
     */
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    /**
     * Popula a tabela com a lista de alunos
     */
    public static void carregarTabela() {
        List<Emprestimo> lista = new EmprestimoControl().getEmprestimos();

        EmprestimosAtivosTM emprestimoTM = new EmprestimosAtivosTM(lista);
        tableEmprestimosLista.setModel(emprestimoTM);
        tableEmprestimosLista.getColumnModel().getColumn(0).setPreferredWidth(50);
        tableEmprestimosLista.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableEmprestimosLista.getColumnModel().getColumn(2).setPreferredWidth(100);
        tableEmprestimosLista.getColumnModel().getColumn(3).setPreferredWidth(200);
        tableEmprestimosLista.getColumnModel().getColumn(4).setPreferredWidth(100);
        tableEmprestimosLista.getColumnModel().getColumn(5).setPreferredWidth(100);
//        tableEmprestimosLista.getColumnModel().getColumn(6).setPreferredWidth(100);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneLivroLista = new javax.swing.JScrollPane();
        tableEmprestimosLista = new javax.swing.JTable();
        buttonNovo = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Empréstimos Ativos");
        setToolTipText("");

        tableEmprestimosLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Livro", "Edição", "Usuário", "Tipo", "Dt Retrida", "Dt Devolução"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEmprestimosLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableEmprestimosLista.getTableHeader().setReorderingAllowed(false);
        tableEmprestimosLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmprestimosListaMouseClicked(evt);
            }
        });
        scrollPaneLivroLista.setViewportView(tableEmprestimosLista);

        buttonNovo.setText("Emprestar livro");
        buttonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoActionPerformed(evt);
            }
        });

        buttonEditar.setText("Realizar Devolucao");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneLivroLista, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(scrollPaneLivroLista, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNovo)
                    .addComponent(buttonEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableEmprestimosListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmprestimosListaMouseClicked

    }//GEN-LAST:event_tableEmprestimosListaMouseClicked

    private void buttonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoActionPerformed

    }//GEN-LAST:event_buttonNovoActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed

    }//GEN-LAST:event_buttonEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JScrollPane scrollPaneLivroLista;
    public static javax.swing.JTable tableEmprestimosLista;
    // End of variables declaration//GEN-END:variables
}
