/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 * Principal
 *
 * @author Jean Barcellos <jeanbarcellos@hotmail.com>
 */
public class Principal extends javax.swing.JFrame {

    private static final long serialVersionUID = 7695201886374250202L;

    /**
     * Creates new form PrincipalTela
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuItemCadastroCurso = new javax.swing.JMenuItem();
        menuItemCadastroAluno = new javax.swing.JMenuItem();
        menuItemCadastroProfessor = new javax.swing.JMenuItem();
        menuItemCadastroLivro = new javax.swing.JMenuItem();
        menuEmprstimos = new javax.swing.JMenu();
        menuItemEmprestimoEmprestar = new javax.swing.JMenuItem();
        menuItemEmprestimosAtivos = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Universitária");
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setName("framePrincipal"); // NOI18N

        desktop.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/page_edit.png"))); // NOI18N
        menuCadastro.setText("Cadastro");

        menuItemCadastroCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/folder.png"))); // NOI18N
        menuItemCadastroCurso.setText("Cursos");
        menuItemCadastroCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroCursoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroCurso);

        menuItemCadastroAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/user.png"))); // NOI18N
        menuItemCadastroAluno.setText("Alunos");
        menuItemCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroAlunoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroAluno);

        menuItemCadastroProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/user_gray.png"))); // NOI18N
        menuItemCadastroProfessor.setText("Professores");
        menuItemCadastroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroProfessorActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroProfessor);

        menuItemCadastroLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/book_open.png"))); // NOI18N
        menuItemCadastroLivro.setText("Livros e Exemplares");
        menuItemCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroLivroActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroLivro);

        barraMenuPrincipal.add(menuCadastro);

        menuEmprstimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/cog.png"))); // NOI18N
        menuEmprstimos.setText("Emprestimos");

        menuItemEmprestimoEmprestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/book_add.png"))); // NOI18N
        menuItemEmprestimoEmprestar.setText("Emprestar Exemplar");
        menuItemEmprestimoEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmprestimoEmprestarActionPerformed(evt);
            }
        });
        menuEmprstimos.add(menuItemEmprestimoEmprestar);

        menuItemEmprestimosAtivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/book_addresses.png"))); // NOI18N
        menuItemEmprestimosAtivos.setText("Empréstimos Ativos");
        menuItemEmprestimosAtivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmprestimosAtivosActionPerformed(evt);
            }
        });
        menuEmprstimos.add(menuItemEmprestimosAtivos);

        barraMenuPrincipal.add(menuEmprstimos);

        menuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/server.png"))); // NOI18N
        menuSistema.setText("Sistema");

        menuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/stop.png"))); // NOI18N
        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuSistema.add(menuItemSair);

        barraMenuPrincipal.add(menuSistema);

        setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        getAccessibleContext().setAccessibleDescription("Biblioteca Universitária");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * EVENTOS *****************************************************************
     */
    private void menuItemCadastroCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroCursoActionPerformed
        this.desktop.removeAll();

        CadastroCursoView cadastroCursoView = new CadastroCursoView();
        desktop.add(cadastroCursoView);
        cadastroCursoView.setPosicao();
        cadastroCursoView.setVisible(true);
    }//GEN-LAST:event_menuItemCadastroCursoActionPerformed

    private void menuItemCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroAlunoActionPerformed
        desktop.removeAll();

        // View de Cadastros
        CadastroAlunoView cadastroAlunoView = new CadastroAlunoView();
        desktop.add(cadastroAlunoView);
        cadastroAlunoView.setPosicao();
        cadastroAlunoView.setVisible(true);
    }//GEN-LAST:event_menuItemCadastroAlunoActionPerformed

    private void menuItemCadastroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroProfessorActionPerformed
        desktop.removeAll();

        CadastroProfessorView cadastroProfessorView = new CadastroProfessorView();
        desktop.add(cadastroProfessorView);
        cadastroProfessorView.setPosicao();
        cadastroProfessorView.setVisible(true);
    }//GEN-LAST:event_menuItemCadastroProfessorActionPerformed

    private void menuItemCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroLivroActionPerformed
        desktop.removeAll();

        CadastroLivroView cadastroLivroView = new CadastroLivroView();
        desktop.add(cadastroLivroView);
        cadastroLivroView.setPosicao();
        cadastroLivroView.setVisible(true);
    }//GEN-LAST:event_menuItemCadastroLivroActionPerformed

    private void menuItemEmprestimosAtivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmprestimosAtivosActionPerformed
        desktop.removeAll();

        EmprestimoLivroView emprestimoView = new EmprestimoLivroView();
        desktop.add(emprestimoView);
        emprestimoView.setPosicao();
        emprestimoView.setVisible(true);
    }//GEN-LAST:event_menuItemEmprestimosAtivosActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemEmprestimoEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmprestimoEmprestarActionPerformed
        desktop.removeAll();

        EmprestimoEmprestarView emprestimoEmprestarView = new EmprestimoEmprestarView();
        desktop.add(emprestimoEmprestarView);
        emprestimoEmprestarView.setPosicao();
        emprestimoEmprestarView.setVisible(true);
    }//GEN-LAST:event_menuItemEmprestimoEmprestarActionPerformed

    /**
     * Classe Principal
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                Nimbus // Windows
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame framePrincipal = new Principal();
//                framePrincipal.setExtendedState(framePrincipal.getExtendedState() | JFrame.MAXIMIZED_BOTH);
                framePrincipal.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenuPrincipal;
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuEmprstimos;
    private javax.swing.JMenuItem menuItemCadastroAluno;
    private javax.swing.JMenuItem menuItemCadastroCurso;
    private javax.swing.JMenuItem menuItemCadastroLivro;
    private javax.swing.JMenuItem menuItemCadastroProfessor;
    private javax.swing.JMenuItem menuItemEmprestimoEmprestar;
    private javax.swing.JMenuItem menuItemEmprestimosAtivos;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuSistema;
    // End of variables declaration//GEN-END:variables
}
